---
# ===========================================================
# Playbook principal : configuration de base des machines
# ===========================================================

- name: Configuration des serveurs Debian via le r√¥le "base"
  hosts: debian
  become: yes
  gather_facts: yes

  roles:
    - base

