---
# ===========================================================
# Playbook principal : configuration de base des machines
# ===========================================================

- name: Configuration des serveurs Debian via le r√¥le "base"
  hosts: baseGroup
  become: yes
  gather_facts: yes

  roles:
    - base

- name: WikiJS servers
  hosts: wikijsGroup
  become: yes
  roles:
    - wikijs
  vars_files:
    - roles/wikijs/vars/vars.yml
    - roles/wikijs/vars/vars_vault.yml


